// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// sdbm_hash
std::vector < unsigned int > sdbm_hash(std::vector < std::string> x);
RcppExport SEXP hrbrmisc_sdbm_hash(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< std::vector < std::string> >::type x(xSEXP);
    __result = Rcpp::wrap(sdbm_hash(x));
    return __result;
END_RCPP
}
